### ISSUE TITLE
Error in cnn_feature_extractor.py 

### ISSUE THREAD

**Issue by Kirthana30** [cesc-park/attend2u#7]
i keep getting errors saying that unexpected keyword arguments for is_training in line 111
![screenshot from 2017-11-20 22-22-13](https://user-images.githubusercontent.com/33656707/33122853-5dbee1d6-cfb3-11e7-83b7-ad186a4a76e7.png)
Can anyone help me to resolve it?

**Comment by cesc-park** [comment]
What's your tensorflow version?
This is a problem caused by tensorflow version. (tf1.3 or higher version does not need "is_training" argument for "resnet_v1_101" function)
I will change the code to work even in higher versions, but I recommend lowering tensorflow version (v1.0 or v1.1) as it can cause other problems depending on it.

**Comment by cesc-park** [comment]
What's your tensorflow version?
This is a problem caused by tensorflow version. (v1.2 or higher version needs "is_training" argument for "resnet_v1_101" function)
I recommend using higher tensorflow version (v1.2 or higher version ).

**Comment by Kirthana30** [comment]
I'm using tensorflow 0.12 version. Is there any other option?

**Comment by Kirthana30** [comment]
i tried to create virtual environment and installed tensorflow version 1.3, it still gives me the same error.

**Comment by cesc-park** [comment]
I'm very sorry about it, please try it with v1.1.0rc2. (or v1.1 maybe)
